language: perl
sudo: true
matrix:
  include:
    # start the first coverage early so that it starts before everything else
    - perl: "5.30"
      env: COVERAGE=1
    - perl: "5.10"
    - perl: "5.12"
    - perl: "5.14"
    - perl: "5.16"
    - perl: "5.18"
    - perl: "blead"
    - perl: "5.20"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - export SPLIT_BUILD=0
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
install:
  - cpan-install --deps       # installs prereqs, including recommends
  - cpan-install --coverage   # installs coverage prereqs, if enabled
  # SYSTEM_CORES set by travis-perl-helpers
  - if [ "$SERIAL_BUILD" == 1 ]; then make; else make -j$(( $SYSTEM_CORES * 2 )); fi
before_script:
  - coverage-setup
script:
  - if [ "$SERIAL_TESTING" == 1 ]; then prove -bv $(test-files); else prove --formatter TAP::Formatter::File -j$(test-jobs) -bv $(test-files); fi
after_success:
  - coverage-report
branches:
  except:
    - /^wip\//
    - /^blocked/
  only:
    - master
notifications:
  irc:
    channels:
      - "irc.perl.org#pdl"
    skip_join: true
